POST http://localhost:4000/api/equipos
Content-Type: application/json

{
    
    "serialnumber":"1234",
    "brand":"prroPanzon",
    "model":"pp20",
    "password":"prueba+2020",
    "systemtype":"win",
    "cpu":"prueba"
    
}